// ============================================================
// EXTENSÃO DO BANCO DE PERGUNTAS - WAVE 2
// Adiciona 15 novas perguntas por tema/dificuldade (420 extras)
// Importado e mesclado pelo quizbank.js
// ============================================================

const BANCO_EXTRA = {

  geral: {
    facil: [
      { p: "Qual é o maior felino do mundo?", v: "Tigre", f: ["Leão", "Onça", "Leopardo"], img: "tiger in the wild jungle stripes" },
      { p: "Quantas cores tem o arco-íris?", v: "7 cores", f: ["5 cores", "6 cores", "8 cores"], img: "rainbow colors in the sky after rain" },
      { p: "Qual é o satélite natural da Terra?", v: "Lua", f: ["Sol", "Marte", "Estrela"], img: "full moon in a clear night sky" },
      { p: "Qual fruta é usada para fazer vinho?", v: "Uva", f: ["Maçã", "Laranja", "Manga"], img: "vineyard with ripe grapes on vines" },
      { p: "Qual órgão usamos para ver?", v: "Olhos", f: ["Ouvidos", "Nariz", "Boca"], img: "human eye close-up iris detail" },
      { p: "Qual material é usado para fazer vidro?", v: "Areia (sílica)", f: ["Argila", "Ferro", "Plástico"], img: "glass blowing molten glass art" },
      { p: "Qual é o país mais populoso da Europa?", v: "Rússia", f: ["Alemanha", "França", "Reino Unido"], img: "Moscow Russia Red Square Kremlin" },
      { p: "Quantas estações do ano existem?", v: "4 estações", f: ["3 estações", "5 estações", "2 estações"], img: "four seasons tree spring summer fall winter" },
      { p: "Qual é o idioma mais falado no mundo?", v: "Inglês (como segunda língua)", f: ["Espanhol", "Francês", "Árabe"], img: "world languages globe communication" },
      { p: "Qual animal é o mais rápido da terra?", v: "Guepardo", f: ["Leão", "Cavalo", "Avestruz"], img: "cheetah running at full speed savanna" },
      { p: "Qual é o principal ingrediente do pão?", v: "Farinha de trigo", f: ["Arroz", "Milho", "Aveia"], img: "fresh baked bread loaves bakery" },
      { p: "Qual é o maior órgão do corpo humano?", v: "Pele", f: ["Fígado", "Pulmão", "Intestino"], img: "human skin layers cross section medical" },
      { p: "Quantos zeros tem um milhão?", v: "6 zeros", f: ["5 zeros", "7 zeros", "8 zeros"], img: "number one million written on blackboard" },
      { p: "Qual pássaro não voa e vive no gelo?", v: "Pinguim", f: ["Avestruz", "Kiwi", "Emu"], img: "penguins on ice in Antarctica" },
      { p: "Qual é a bebida mais consumida no mundo depois da água?", v: "Chá", f: ["Café", "Suco", "Refrigerante"], img: "cup of tea with leaves steam rising" }
    ],
    medio: [
      { p: "Qual instrumento mede a temperatura?", v: "Termômetro", f: ["Barômetro", "Higrômetro", "Anemômetro"], img: "mercury thermometer measuring temperature" },
      { p: "Qual é a montanha mais alta do mundo?", v: "Monte Everest", f: ["K2", "Kangchenjunga", "Monte Branco"], img: "Mount Everest snow peak Himalayas" },
      { p: "Qual cientista formulou as leis da gravidade?", v: "Isaac Newton", f: ["Galileu", "Einstein", "Copérnico"], img: "Newton apple tree gravity discovery" },
      { p: "Qual é o menor continente do mundo?", v: "Oceania", f: ["Europa", "Antártica", "América Central"], img: "Oceania Australia continent map aerial" },
      { p: "Qual país inventou a pizza?", v: "Itália", f: ["EUA", "Grécia", "França"], img: "Italian pizza Margherita fresh from oven" },
      { p: "Qual é o animal mais venenoso do mundo?", v: "Vespa-do-mar (box jellyfish)", f: ["Cobra-rei", "Aranha-armadeira", "Escorpião"], img: "box jellyfish transparent ocean dangerous" },
      { p: "Qual escritor brasileiro escreveu 'Dom Casmurro'?", v: "Machado de Assis", f: ["José de Alencar", "Jorge Amado", "Clarice Lispector"], img: "old Brazilian literature book vintage" },
      { p: "Qual país tem formato de bota no mapa?", v: "Itália", f: ["Portugal", "Grécia", "Croácia"], img: "Italy boot shape map Mediterranean" },
      { p: "Qual é o animal mais alto do mundo?", v: "Girafa", f: ["Elefante", "Camelo", "Avestruz"], img: "tall giraffe eating from tree African savanna" },
      { p: "Qual é o rio mais largo do mundo?", v: "Rio Amazonas", f: ["Rio Nilo", "Rio Mississipi", "Rio Congo"], img: "Amazon River wide aerial view rainforest" },
      { p: "Qual planeta é conhecido como Gigante Gasoso?", v: "Júpiter", f: ["Marte", "Urano", "Mercúrio"], img: "Jupiter gas giant planet swirling clouds" },
      { p: "Qual é a unidade de medida de peso no SI?", v: "Quilograma (kg)", f: ["Libra", "Onça", "Grama"], img: "precision scale weight measurement" },
      { p: "Qual doença é causada pela falta de vitamina C?", v: "Escorbuto", f: ["Raquitismo", "Beribéri", "Pelagra"], img: "citrus fruits vitamin C oranges lemons" },
      { p: "Qual país é o maior exportador de café?", v: "Brasil", f: ["Colômbia", "Vietnã", "Etiópia"], img: "coffee beans plantation Brazil harvest" },
      { p: "Qual órgão filtra o sangue no corpo humano?", v: "Rins", f: ["Fígado", "Baço", "Pâncreas"], img: "kidney organ anatomy medical illustration" }
    ],
    dificil: [
      { p: "Qual é o composto químico mais comum na crosta terrestre?", v: "Dióxido de silício (SiO2)", f: ["Óxido de alumínio", "Carbonato de cálcio", "Óxido de ferro"], img: "quartz crystal silicon dioxide mineral" },
      { p: "Qual país tem mais Patrimônios da UNESCO?", v: "Itália", f: ["China", "Espanha", "França"], img: "UNESCO World Heritage sites collage" },
      { p: "Qual fenômeno óptico cria miragens no deserto?", v: "Refração da luz", f: ["Reflexão", "Difração", "Polarização"], img: "desert mirage optical illusion heat" },
      { p: "Qual é o material mais duro da natureza?", v: "Diamante", f: ["Rubi", "Safira", "Quartzo"], img: "diamond crystal sparkling brilliant" },
      { p: "Qual é o oceano mais salgado do mundo?", v: "Oceano Atlântico", f: ["Oceano Pacífico", "Oceano Índico", "Oceano Ártico"], img: "Atlantic Ocean salt water waves aerial" },
      { p: "Qual cientista descobriu os raios X?", v: "Wilhelm Röntgen", f: ["Marie Curie", "Nikola Tesla", "Michael Faraday"], img: "X-ray discovery hand bone vintage" },
      { p: "Qual é a maior cachoeira do mundo em volume?", v: "Cataratas do Niágara", f: ["Cataratas do Iguaçu", "Salto Angel", "Cachoeira Victoria"], img: "Niagara Falls massive water volume" },
      { p: "Qual é o animal que vive mais tempo?", v: "Tartaruga-gigante (~200 anos)", f: ["Baleia-da-groenlândia", "Elefante", "Papagaio"], img: "giant tortoise old ancient reptile" },
      { p: "Qual é o idioma oficial da Etiópia?", v: "Amárico", f: ["Suaíli", "Árabe", "Inglês"], img: "Ethiopian Amharic script ancient text" },
      { p: "Qual compositor escreveu a 'Nona Sinfonia'?", v: "Beethoven", f: ["Mozart", "Bach", "Brahms"], img: "Beethoven Ninth Symphony orchestra sheet music" },
      { p: "Qual é a única fruta que tem sementes por fora?", v: "Morango", f: ["Framboesa", "Amora", "Kiwi"], img: "strawberry seeds on surface macro" },
      { p: "Qual civilização criou os Jogos Olímpicos?", v: "Gregos", f: ["Romanos", "Egípcios", "Persas"], img: "ancient Greek Olympic Games stadium" },
      { p: "Qual é o gás nobre mais leve?", v: "Hélio", f: ["Neônio", "Argônio", "Criptônio"], img: "helium balloons floating in the sky" },
      { p: "Qual pintor cortou a própria orelha?", v: "Van Gogh", f: ["Monet", "Picasso", "Dalí"], img: "sunflowers painting impressionist style" },
      { p: "Qual é o animal terrestre mais pesado?", v: "Elefante africano", f: ["Rinoceronte branco", "Hipopótamo", "Girafa"], img: "massive African elephant in the wild" }
    ],
    infernal: [
      { p: "Qual é o nome do efeito que faz abelhas dançarem para comunicar?", v: "Dança do oito (waggle dance)", f: ["Dança circular", "Efeito colmeia", "Sinal feromonial"], img: "bee waggle dance communication hive" },
      { p: "Qual é o isótopo mais estável do carbono?", v: "Carbono-12", f: ["Carbono-14", "Carbono-13", "Carbono-11"], img: "carbon isotope atomic structure diagram" },
      { p: "Qual peixe pode gerar eletricidade?", v: "Poraquê (enguia-elétrica)", f: ["Peixe-gato", "Arraia", "Baiacu"], img: "electric eel generating electricity underwater" },
      { p: "Qual é a unidade de medida de luminosidade estelar?", v: "Magnitude", f: ["Lúmen", "Candela", "Lux"], img: "stellar magnitude brightness comparison stars" },
      { p: "Qual cientista propôs a tabela periódica?", v: "Mendeleev", f: ["Dalton", "Lavoisier", "Bohr"], img: "periodic table of elements chemistry" },
      { p: "Qual país tem a maior biodiversidade do mundo?", v: "Brasil", f: ["Colômbia", "Indonésia", "México"], img: "Amazon rainforest biodiversity wildlife" },
      { p: "Qual é o nome da hipótese sobre a Terra como organismo vivo?", v: "Hipótese de Gaia", f: ["Teoria de Pangeia", "Hipótese de Drake", "Paradoxo de Fermi"], img: "Earth as living organism Gaia concept" },
      { p: "Qual é o maior vulcão do sistema solar?", v: "Olympus Mons (Marte)", f: ["Mauna Kea", "Monte Etna", "Mons Huygens"], img: "Olympus Mons Mars giant volcano" },
      { p: "Qual é a profundidade média dos oceanos?", v: "~3.688 metros", f: ["~2.000 metros", "~5.000 metros", "~1.500 metros"], img: "ocean depth chart cross section deep" },
      { p: "Qual filósofo disse 'Penso, logo existo'?", v: "René Descartes", f: ["Platão", "Aristóteles", "Kant"], img: "philosophical thought bubble brain thinking" },
      { p: "Qual é o ponto mais ao norte da Terra?", v: "Polo Norte geográfico", f: ["Polo Norte magnético", "Cabo Norte", "Ilha Ellesmere"], img: "North Pole Arctic ice frozen landscape" },
      { p: "Qual animal marinho tem 3 corações?", v: "Polvo", f: ["Lula", "Água-viva", "Cavalo-marinho"], img: "octopus three hearts anatomy illustration" },
      { p: "Qual é o evento de extinção mais recente?", v: "Extinção do Holoceno (atual)", f: ["Cretáceo-Paleogeno", "Permiano-Triássico", "Devoniano"], img: "endangered species extinction concept" },
      { p: "Qual é a fórmula da energia cinética?", v: "½mv²", f: ["mgh", "F=ma", "E=mc²"], img: "kinetic energy physics formula motion" },
      { p: "Qual fenômeno faz o céu ser azul?", v: "Espalhamento de Rayleigh", f: ["Reflexão do mar", "Refração atmosférica", "Efeito Doppler"], img: "blue sky sunlight scattering atmosphere" }
    ]
  },

  historia: {
    facil: [
      { p: "Qual é a capital da França?", v: "Paris", f: ["Lyon", "Marselha", "Nice"], img: "Paris France Eiffel Tower cityscape" },
      { p: "Qual oceano banha o leste do Brasil?", v: "Oceano Atlântico", f: ["Oceano Pacífico", "Oceano Índico", "Mar Mediterrâneo"], img: "Brazilian coastline Atlantic Ocean aerial" },
      { p: "Quem foi Cleópatra?", v: "Rainha do Egito", f: ["Rainha de Roma", "Rainha da Grécia", "Rainha da Pérsia"], img: "ancient Egyptian queen pharaoh throne" },
      { p: "Qual monumento tem a estátua do Cristo Redentor?", v: "Corcovado (Rio de Janeiro)", f: ["Pão de Açúcar", "Maracanã", "Serra da Canastra"], img: "Christ the Redeemer statue Rio de Janeiro" },
      { p: "Qual povo construiu os castelos medievais?", v: "Europeus (feudais)", f: ["Chineses", "Egípcios", "Astecas"], img: "medieval castle fortress Europe" },
      { p: "Qual é a capital do México?", v: "Cidade do México", f: ["Cancún", "Guadalajara", "Monterrey"], img: "Mexico City Zocalo Plaza historic center" },
      { p: "Qual documento declarou a independência dos EUA?", v: "Declaração de Independência", f: ["Constituição", "Carta Magna", "Bill of Rights"], img: "US Declaration of Independence document" },
      { p: "Qual era a profissão de Cristóvão Colombo?", v: "Navegador/explorador", f: ["Rei", "Soldado", "Padre"], img: "Christopher Columbus ships sailing ocean" },
      { p: "Qual país construiu o Canal de Panamá?", v: "EUA (com franceses antes)", f: ["Inglaterra", "Espanha", "Panamá"], img: "Panama Canal ships passing through locks" },
      { p: "Qual civilização vivia no México antes dos espanhóis?", v: "Astecas", f: ["Incas", "Maias apenas", "Romanos"], img: "Aztec pyramid Tenochtitlan ancient Mexico" },
      { p: "Qual continente tem mais países?", v: "África", f: ["Ásia", "Europa", "América"], img: "Africa continent map with countries" },
      { p: "Qual era o transporte mais comum no Egito Antigo?", v: "Barco pelo Nilo", f: ["Carruagem", "Camelo", "Cavalo"], img: "ancient Egyptian boat sailing on Nile" },
      { p: "Qual é a capital do Japão?", v: "Tóquio", f: ["Osaka", "Quioto", "Nagoya"], img: "Tokyo Japan skyline modern city" },
      { p: "Qual povo inventou o papel?", v: "Chineses", f: ["Egípcios", "Gregos", "Romanos"], img: "ancient Chinese papermaking invention" },
      { p: "Qual bandeira tem uma folha de maple?", v: "Canadá", f: ["EUA", "Austrália", "Nova Zelândia"], img: "Canadian flag red maple leaf" }
    ],
    medio: [
      { p: "Qual imperador coroou a si mesmo?", v: "Napoleão Bonaparte", f: ["Carlos Magno", "César Augusto", "Alexandre, o Grande"], img: "Napoleon coronation self-crowning painting" },
      { p: "Qual país lançou as bombas atômicas na II Guerra?", v: "EUA", f: ["Inglaterra", "URSS", "Alemanha"], img: "atomic bomb mushroom cloud historical" },
      { p: "Qual rio divide a cidade de Londres?", v: "Rio Tâmisa", f: ["Rio Sena", "Rio Reno", "Rio Danúbio"], img: "Thames River London Tower Bridge" },
      { p: "Qual era a religião oficial do Império Otomano?", v: "Islamismo", f: ["Cristianismo", "Judaísmo", "Budismo"], img: "Ottoman Empire mosque Istanbul" },
      { p: "Qual foi o primeiro país a abolir a escravidão?", v: "Haiti (1804)", f: ["Inglaterra", "França", "EUA"], img: "Haitian revolution freedom historical" },
      { p: "Qual guerra durou de 1955 a 1975?", v: "Guerra do Vietnã", f: ["Guerra da Coreia", "Guerra Fria", "Guerra do Golfo"], img: "Vietnam War jungle helicopter historical" },
      { p: "Qual cidade foi capital do Império Bizantino?", v: "Constantinopla", f: ["Roma", "Atenas", "Alexandria"], img: "Constantinople Byzantine Hagia Sophia" },
      { p: "Qual é o nome do faraó mais famoso?", v: "Tutancâmon", f: ["Ramsés II", "Cleópatra", "Akhenaton"], img: "Tutankhamun golden mask Egyptian pharaoh" },
      { p: "Em que continente surgiu a humanidade?", v: "África", f: ["Ásia", "Europa", "América"], img: "African savanna early human evolution" },
      { p: "Qual foi o nome da operação aliada no Dia D?", v: "Operação Overlord", f: ["Operação Barbarossa", "Operação Market Garden", "Operação Torch"], img: "D-Day Normandy beach landing World War II" },
      { p: "Qual era a capital do Império Persa?", v: "Persépolis", f: ["Babilônia", "Atenas", "Tebas"], img: "Persepolis ancient Persian palace ruins" },
      { p: "Qual presidente americano libertou os escravos?", v: "Abraham Lincoln", f: ["George Washington", "Thomas Jefferson", "Theodore Roosevelt"], img: "Abraham Lincoln memorial statue" },
      { p: "Qual país foi unificado por Bismarck?", v: "Alemanha", f: ["Itália", "Espanha", "Áustria"], img: "German unification Bismarck Iron Chancellor" },
      { p: "Qual civilização construiu estradas por todo seu império?", v: "Romanos", f: ["Gregos", "Persas", "Egípcios"], img: "ancient Roman road cobblestone path" },
      { p: "Qual é o nome do período artístico após a Idade Média?", v: "Renascimento", f: ["Barroco", "Gótico", "Romantismo"], img: "Renaissance art painting Florence Italy" }
    ],
    dificil: [
      { p: "Qual é o código legal mais antigo ainda parcialmente em uso?", v: "Direito Romano", f: ["Código de Hamurabi", "Lei das XII Tábuas", "Lei de Manu"], img: "Roman law ancient legal tablets" },
      { p: "Qual dinastia governou a China por mais tempo?", v: "Dinastia Zhou (~800 anos)", f: ["Dinastia Han", "Dinastia Ming", "Dinastia Tang"], img: "ancient Chinese dynasty bronze vessels" },
      { p: "Qual explorador chegou primeiro ao Polo Sul?", v: "Roald Amundsen", f: ["Robert Scott", "Ernest Shackleton", "James Cook"], img: "South Pole expedition flag ice Antarctic" },
      { p: "Qual guerra civil matou mais pessoas na história?", v: "Rebelião Taiping (China)", f: ["Guerra Civil Americana", "Guerra Civil Russa", "Guerra Civil Espanhola"], img: "Taiping Rebellion China historical battle" },
      { p: "Qual era a moeda do Império Romano?", v: "Denário", f: ["Dracma", "Sestércio", "Solidus"], img: "ancient Roman denarius coin emperor" },
      { p: "Qual navegador português descobriu o caminho marítimo para a Índia?", v: "Vasco da Gama", f: ["Pedro Álvares Cabral", "Bartolomeu Dias", "Fernão de Magalhães"], img: "Portuguese ship sailing Indian Ocean route" },
      { p: "Qual era o sistema econômico da URSS?", v: "Socialismo/Comunismo", f: ["Capitalismo", "Feudalismo", "Mercantilismo"], img: "Soviet Union USSR hammer sickle flag" },
      { p: "Qual país se separou do Paquistão em 1971?", v: "Bangladesh", f: ["Sri Lanka", "Nepal", "Myanmar"], img: "Bangladesh independence 1971 historical" },
      { p: "Qual foi a última colônia europeia na América?", v: "Guiana (1966)", f: ["Suriname", "Belize", "Jamaica"], img: "British Guiana colonial era map" },
      { p: "Qual imperador romano incendiou Roma?", v: "Nero (atribuído)", f: ["Calígula", "Cômodo", "Domiciano"], img: "Rome burning Great Fire Nero historical" },
      { p: "Qual povo criou o alfabeto que originou o latino?", v: "Fenícios", f: ["Gregos", "Egípcios", "Sumérios"], img: "Phoenician alphabet ancient letters" },
      { p: "Qual evento marcou o início da Idade Média?", v: "Queda de Roma (476 d.C.)", f: ["Cruzadas", "Peste Negra", "Nascimento de Cristo"], img: "Fall of Roman Empire barbarian invasion" },
      { p: "Qual país europeu dominou o comércio de especiarias no séc. XVI?", v: "Portugal", f: ["Espanha", "Holanda", "Inglaterra"], img: "spice trade Portuguese ships 16th century" },
      { p: "Qual era a religião dos Vikings?", v: "Paganismo nórdico", f: ["Cristianismo", "Islamismo", "Budismo"], img: "Norse mythology Odin Valhalla Viking" },
      { p: "Qual tratado encerrou a Guerra dos Trinta Anos?", v: "Paz de Vestfália (1648)", f: ["Tratado de Utrecht", "Tratado de Paris", "Tratado de Viena"], img: "Peace of Westphalia treaty 1648 painting" }
    ],
    infernal: [
      { p: "Qual é o nome do mais antigo texto literário conhecido?", v: "Epopeia de Gilgamesh", f: ["Ilíada", "Bíblia", "Vedas"], img: "Epic of Gilgamesh ancient clay tablet" },
      { p: "Qual cidade foi capital de três impérios diferentes?", v: "Istambul (Roma/Bizantino/Otomano)", f: ["Roma", "Bagdá", "Cairo"], img: "Istanbul three empires historical mosques" },
      { p: "Qual dinastia japonesa governa desde 660 a.C. (segundo tradição)?", v: "Dinastia Imperial (Yamato)", f: ["Shogunato Tokugawa", "Clã Fujiwara", "Clã Minamoto"], img: "Japanese Imperial chrysanthemum throne" },
      { p: "Qual era o principal produto exportado pelo Brasil Colônia no séc. XVII?", v: "Açúcar", f: ["Ouro", "Café", "Pau-brasil"], img: "sugar cane plantation colonial Brazil" },
      { p: "Qual civilização pré-colombiana praticava sacrifícios humanos em massa?", v: "Astecas", f: ["Maias", "Incas", "Olmecas"], img: "Aztec temple sacrifice pyramid Tenochtitlan" },
      { p: "Qual é o nome do acordo que dividiu a África em 1884?", v: "Conferência de Berlim", f: ["Congresso de Viena", "Tratado de Versalhes", "Acordo de Yalta"], img: "Berlin Conference Africa partition map 1884" },
      { p: "Qual batalha naval derrotou a Armada Espanhola em 1588?", v: "Batalha de Gravelines", f: ["Batalha de Trafalgar", "Batalha de Lepanto", "Batalha do Nilo"], img: "Spanish Armada naval battle 1588" },
      { p: "Qual foi a primeira república da América Latina?", v: "Haiti (1804)", f: ["México (1821)", "Brasil (1889)", "Argentina (1816)"], img: "Haitian revolution first Latin American republic" },
      { p: "Qual era o nome do parlamento da República Romana?", v: "Senado", f: ["Ágora", "Assembleia", "Comício"], img: "Roman Senate ancient political chamber" },
      { p: "Qual explorador cruzou o Estreito de Drake pela primeira vez?", v: "Francis Drake", f: ["Fernão de Magalhães", "James Cook", "Vasco da Gama"], img: "Drake Passage stormy seas Antarctic" },
      { p: "Qual imperador mongol tinha a maior extensão territorial?", v: "Genghis Khan / Kublai Khan", f: ["Tamerlão", "Átila", "Alexandre"], img: "Mongol Empire vast territory horseback" },
      { p: "Qual foi o primeiro tratado de comércio internacional?", v: "Tratado de Nanquim (1842)", f: ["Tratado de Tordesilhas", "Tratado de Versalhes", "Congresso de Viena"], img: "Nanjing Treaty historical China Britain" },
      { p: "Qual invenção chinesa mudou a guerra medieval?", v: "Pólvora", f: ["Bússola", "Papel", "Seda"], img: "gunpowder explosion medieval warfare Chinese" },
      { p: "Qual foi o maior império em área da história?", v: "Império Britânico", f: ["Império Mongol", "Império Romano", "Império Russo"], img: "British Empire world map red territories" },
      { p: "Qual povo construiu a cidade de Cartago?", v: "Fenícios", f: ["Romanos", "Gregos", "Egípcios"], img: "Carthage ruins ancient Phoenician city" }
    ]
  },

  ciencia: {
    facil: [
      { p: "Qual planeta é o mais próximo do Sol?", v: "Mercúrio", f: ["Vênus", "Terra", "Marte"], img: "Mercury planet closest to the Sun" },
      { p: "Qual é o material mais leve: ferro ou madeira?", v: "Madeira", f: ["Ferro", "São iguais", "Depende"], img: "wood and iron comparison materials" },
      { p: "Quantos sentidos o ser humano tem?", v: "5 sentidos", f: ["4 sentidos", "6 sentidos", "3 sentidos"], img: "five senses human body illustration" },
      { p: "Qual é o principal alimento das baleias?", v: "Krill / plâncton", f: ["Peixes grandes", "Algas", "Lulas"], img: "whale feeding on krill ocean" },
      { p: "De que cor é o sangue humano dentro do corpo?", v: "Vermelho", f: ["Azul", "Roxo", "Transparente"], img: "red blood cells flowing through veins" },
      { p: "Qual é o animal mais lento do mundo?", v: "Preguiça", f: ["Tartaruga", "Caracol", "Lesma"], img: "sloth hanging slowly from tree branch" },
      { p: "O que acontece quando a água congela?", v: "Vira gelo (sólido)", f: ["Evapora", "Desaparece", "Fica mais densa"], img: "ice cubes freezing water crystal clear" },
      { p: "Qual parte da planta absorve água do solo?", v: "Raiz", f: ["Folha", "Caule", "Flor"], img: "plant roots absorbing water from soil" },
      { p: "Qual é o planeta mais distante do Sol?", v: "Netuno", f: ["Plutão", "Urano", "Saturno"], img: "Neptune blue planet far from Sun space" },
      { p: "Qual tipo de animal é a baleia?", v: "Mamífero", f: ["Peixe", "Réptil", "Anfíbio"], img: "blue whale breaching ocean surface" },
      { p: "Qual é o osso mais duro do corpo humano?", v: "Esmalte do dente", f: ["Fêmur", "Crânio", "Costela"], img: "human tooth enamel cross section dental" },
      { p: "Qual astro ilumina a noite refletindo a luz do Sol?", v: "Lua", f: ["Estrelas", "Júpiter", "Vênus"], img: "moon reflecting sunlight night sky" },
      { p: "Qual gás é liberado pelas plantas na fotossíntese?", v: "Oxigênio", f: ["Gás carbônico", "Nitrogênio", "Hidrogênio"], img: "plant releasing oxygen photosynthesis" },
      { p: "Qual animal produz seda?", v: "Bicho-da-seda", f: ["Aranha", "Abelha", "Formiga"], img: "silkworm cocoon silk production" },
      { p: "O que o terremoto mede na escala Richter?", v: "Intensidade do tremor", f: ["Temperatura", "Velocidade do vento", "Altura das ondas"], img: "earthquake seismic waves ground shaking" }
    ],
    medio: [
      { p: "Qual é a lei de Newton que fala sobre ação e reação?", v: "Terceira Lei de Newton", f: ["Primeira Lei", "Segunda Lei", "Lei da Gravitação"], img: "Newton third law action reaction diagram" },
      { p: "Qual é o processo de transformação de larva em borboleta?", v: "Metamorfose", f: ["Evolução", "Mutação", "Hibernação"], img: "butterfly metamorphosis stages cocoon" },
      { p: "Qual cientista descobriu a radioatividade?", v: "Henri Becquerel", f: ["Marie Curie", "Ernest Rutherford", "Niels Bohr"], img: "radioactivity discovery uranium rays" },
      { p: "Qual é a temperatura do corpo humano normal?", v: "~36,5°C", f: ["~38°C", "~35°C", "~40°C"], img: "body temperature thermometer human health" },
      { p: "Qual gás é responsável pelo efeito estufa?", v: "Gás Carbônico (CO2)", f: ["Oxigênio", "Nitrogênio", "Hélio"], img: "greenhouse effect CO2 global warming" },
      { p: "Qual é o nome da força que se opõe ao movimento?", v: "Atrito", f: ["Gravidade", "Inércia", "Impulso"], img: "friction force opposing motion physics" },
      { p: "Qual é o maior satélite de Júpiter?", v: "Ganimedes", f: ["Europa", "Io", "Calisto"], img: "Ganymede Jupiter largest moon space" },
      { p: "Qual hormônio regula o açúcar no sangue?", v: "Insulina", f: ["Adrenalina", "Cortisol", "Melatonina"], img: "insulin hormone diabetes blood sugar" },
      { p: "Qual fenômeno climático aquece o Pacífico?", v: "El Niño", f: ["La Niña", "Monção", "Tornado"], img: "El Nino Pacific Ocean warm current" },
      { p: "Qual é a diferença entre peso e massa?", v: "Peso depende da gravidade, massa não", f: ["São iguais", "Massa é maior", "Peso é constante"], img: "weight vs mass gravity comparison" },
      { p: "Qual é o nome da camada mais externa da Terra?", v: "Crosta (litosfera)", f: ["Manto", "Núcleo", "Astenosfera"], img: "Earth layers crust mantle core cross section" },
      { p: "Qual tipo de célula não tem núcleo?", v: "Hemácia (glóbulo vermelho)", f: ["Neurônio", "Leucócito", "Plaqueta"], img: "red blood cell without nucleus microscope" },
      { p: "Qual é o nome da reação química que libera calor?", v: "Exotérmica", f: ["Endotérmica", "Isotérmica", "Adiabática"], img: "exothermic reaction fire heat energy" },
      { p: "Qual cientista criou a teoria da evolução?", v: "Charles Darwin", f: ["Lamarck", "Mendel", "Linnaeus"], img: "Darwin evolution tree of life species" },
      { p: "Qual tipo de onda é o som?", v: "Onda mecânica longitudinal", f: ["Onda eletromagnética", "Onda transversal", "Onda estacionária"], img: "sound wave compression rarefaction diagram" }
    ],
    dificil: [
      { p: "Qual é o nome da partícula que transmite a força eletromagnética?", v: "Fóton", f: ["Gluon", "Bóson W", "Graviton"], img: "photon electromagnetic force particle physics" },
      { p: "Qual é o menor osso do corpo humano?", v: "Estribo (ouvido)", f: ["Bigorna", "Martelo", "Cóclea"], img: "stapes ear bone smallest human body" },
      { p: "Qual é o estado da matéria do interior do Sol?", v: "Plasma", f: ["Gás", "Líquido", "Sólido"], img: "Sun plasma interior nuclear fusion" },
      { p: "Qual ácido está no vinagre?", v: "Ácido acético", f: ["Ácido cítrico", "Ácido clorídrico", "Ácido sulfúrico"], img: "vinegar acetic acid chemical bottle" },
      { p: "Qual é o componente principal do ar atmosférico?", v: "Nitrogênio (~78%)", f: ["Oxigênio (~78%)", "CO2 (~78%)", "Argônio (~78%)"], img: "atmosphere composition pie chart gases" },
      { p: "Qual teoria explica a formação do universo?", v: "Big Bang", f: ["Estado Estacionário", "Criacionismo", "Universo Cíclico"], img: "Big Bang universe expansion cosmic" },
      { p: "Qual é o processo de divisão celular que gera gametas?", v: "Meiose", f: ["Mitose", "Citocinese", "Apoptose"], img: "meiosis cell division gamete formation" },
      { p: "Qual mineral é o mais comum na crosta terrestre?", v: "Feldspato", f: ["Quartzo", "Mica", "Olivina"], img: "feldspar mineral crystal geology" },
      { p: "Qual tipo de estrela é o Sol?", v: "Anã amarela (G2V)", f: ["Gigante vermelha", "Supergigante", "Anã branca"], img: "Sun yellow dwarf star classification" },
      { p: "Qual é a enzima que copia o DNA?", v: "DNA polimerase", f: ["RNA polimerase", "Helicase", "Ligase"], img: "DNA polymerase replication enzyme" },
      { p: "Qual elemento químico tem o símbolo 'Pb'?", v: "Chumbo", f: ["Fósforo", "Potássio", "Plutônio"], img: "lead Pb element periodic table" },
      { p: "Qual é a lei que relaciona pressão e volume de um gás?", v: "Lei de Boyle", f: ["Lei de Charles", "Lei de Gay-Lussac", "Lei de Dalton"], img: "Boyle law pressure volume gas diagram" },
      { p: "Qual é o nome da nebulosa mais famosa?", v: "Nebulosa de Órion", f: ["Nebulosa do Caranguejo", "Nebulosa da Águia", "Nebulosa Helix"], img: "Orion Nebula colorful gas cloud space" },
      { p: "Qual é a frequência da corrente elétrica no Brasil?", v: "60 Hz", f: ["50 Hz", "70 Hz", "120 Hz"], img: "electrical outlet plug Brazil frequency" },
      { p: "Qual fenômeno faz os continentes se moverem?", v: "Tectônica de placas", f: ["Erosão", "Vulcanismo", "Gravidade lunar"], img: "tectonic plates continental drift Earth" }
    ],
    infernal: [
      { p: "Qual é o nome da constante que relaciona energia e temperatura?", v: "Constante de Boltzmann", f: ["Constante de Planck", "Constante gravitacional", "Constante de Avogadro"], img: "Boltzmann constant statistical mechanics" },
      { p: "Qual é o elemento mais raro na crosta terrestre?", v: "Astato", f: ["Frâncio", "Plutônio", "Promécio"], img: "rare element astatine periodic table" },
      { p: "Qual tipo de radiação é mais penetrante?", v: "Radiação gama", f: ["Radiação alfa", "Radiação beta", "Raios X"], img: "gamma radiation penetration comparison" },
      { p: "Qual é o nome do experimento que provou a dualidade onda-partícula?", v: "Dupla fenda de Young", f: ["Experiência de Michelson-Morley", "Experimento de Stern-Gerlach", "Efeito fotoelétrico"], img: "double slit experiment quantum physics" },
      { p: "Qual é a molécula mais abundante no corpo humano?", v: "Água (H2O)", f: ["Proteína", "DNA", "Lipídios"], img: "water molecule H2O 3D structure" },
      { p: "Qual é o ponto triplo da água?", v: "0,01°C e 611,73 Pa", f: ["0°C e 1 atm", "100°C e 1 atm", "4°C e 1 atm"], img: "water phase diagram triple point" },
      { p: "Qual organela é responsável pela digestão celular?", v: "Lisossomo", f: ["Ribossomo", "Peroxissomo", "Centrossomo"], img: "lysosome cell digestion organelle" },
      { p: "Qual é o nome do ciclo de reações que ocorre nas mitocôndrias?", v: "Ciclo de Krebs", f: ["Ciclo de Calvin", "Glicólise", "Cadeia respiratória"], img: "Krebs cycle mitochondria biochemistry" },
      { p: "Qual é a força nuclear que mantém quarks unidos?", v: "Força forte (mediada por glúons)", f: ["Força fraca", "Força eletromagnética", "Gravidade"], img: "strong nuclear force quarks gluons physics" },
      { p: "Qual é o limite teórico de eficiência de uma máquina térmica?", v: "Ciclo de Carnot", f: ["Ciclo de Otto", "Ciclo de Diesel", "Ciclo de Rankine"], img: "Carnot cycle heat engine efficiency" },
      { p: "Qual proteína transporta oxigênio no sangue?", v: "Hemoglobina", f: ["Albumina", "Fibrinogênio", "Mioglobina"], img: "hemoglobin protein red blood cell oxygen" },
      { p: "Qual cientista formulou a equação de onda para elétrons?", v: "Erwin Schrödinger", f: ["Werner Heisenberg", "Paul Dirac", "Max Born"], img: "Schrodinger wave equation quantum atom" },
      { p: "Qual é a velocidade de escape da Terra?", v: "~11,2 km/s", f: ["~7,9 km/s", "~15 km/s", "~25 km/s"], img: "rocket escape velocity Earth launch" },
      { p: "Qual é o princípio que diz que é impossível determinar posição e momento simultaneamente?", v: "Princípio da Incerteza de Heisenberg", f: ["Princípio da Exclusão de Pauli", "Princípio da Complementaridade", "Princípio de Superposição"], img: "Heisenberg uncertainty principle diagram" },
      { p: "Qual é a menor unidade funcional do rim?", v: "Néfron", f: ["Glomérulo", "Túbulo", "Cálice renal"], img: "nephron kidney functional unit anatomy" }
    ]
  },

  geek: {
    facil: [
      { p: "Qual é o nome do vilão principal do Mario?", v: "Bowser", f: ["Wario", "Donkey Kong", "Koopa"], img: "turtle dragon villain castle fire" },
      { p: "Qual aplicativo tem um fantasma como logo?", v: "Snapchat", f: ["Instagram", "TikTok", "WhatsApp"], img: "ghost logo social media app" },
      { p: "Qual herói usa um escudo de vibranium?", v: "Capitão América", f: ["Thor", "Hulk", "Homem-Aranha"], img: "patriotic shield red white blue hero" },
      { p: "Qual é o nome da princesa que o Mario salva?", v: "Peach", f: ["Zelda", "Daisy", "Rosalina"], img: "princess castle mushroom kingdom" },
      { p: "Qual jogo tem blocos que você quebra com uma bola?", v: "Breakout / Arkanoid", f: ["Pong", "Tetris", "Space Invaders"], img: "brick breaker game colorful blocks" },
      { p: "Qual super-herói é o Deus do Trovão?", v: "Thor", f: ["Zeus", "Hércules", "Odin"], img: "thunder god hammer lightning storm" },
      { p: "Qual rede social tem um pássaro azul como logo?", v: "Twitter/X", f: ["Facebook", "Instagram", "LinkedIn"], img: "blue bird social media logo icon" },
      { p: "Qual personagem de anime tem cabelo loiro e é ninja?", v: "Naruto", f: ["Goku", "Luffy", "Ichigo"], img: "blonde ninja anime character running" },
      { p: "Qual jogo tem aliens pixelados descendo a tela?", v: "Space Invaders", f: ["Galaga", "Asteroids", "Centipede"], img: "pixel aliens descending space invaders retro" },
      { p: "Qual é o nome do robô amarelo dos Transformers?", v: "Bumblebee", f: ["Optimus Prime", "Megatron", "Starscream"], img: "yellow robot car transforming" },
      { p: "Qual console portátil da Nintendo tem duas telas?", v: "Nintendo DS", f: ["Game Boy", "PSP", "Switch"], img: "dual screen portable gaming console" },
      { p: "Qual personagem come fantasmas e pílulas?", v: "Pac-Man", f: ["Mario", "Kirby", "Mega Man"], img: "yellow circle eating dots maze game" },
      { p: "Qual filme animado tem carros que falam?", v: "Carros (Cars)", f: ["Toy Story", "Velozes e Furiosos", "Turbo"], img: "animated talking race car cartoon" },
      { p: "Qual é o nome do cachorro do Mickey Mouse?", v: "Pluto", f: ["Pateta", "Max", "Bolt"], img: "cartoon yellow dog Disney character" },
      { p: "Qual super-herói é 'O Homem Sem Medo'?", v: "Demolidor (Daredevil)", f: ["Batman", "Punisher", "Luke Cage"], img: "blind superhero red costume rooftop night" }
    ],
    medio: [
      { p: "Qual é o nome do reino em que se passa Dark Souls?", v: "Lordran", f: ["Azeroth", "Tamriel", "Hyrule"], img: "dark fantasy kingdom ruins bonfires" },
      { p: "Qual jogo de cartas tem o Blue-Eyes White Dragon?", v: "Yu-Gi-Oh!", f: ["Magic: The Gathering", "Pokémon TCG", "Hearthstone"], img: "dragon card game TCG fantasy" },
      { p: "Qual é o nome do protagonista de Halo?", v: "Master Chief", f: ["Doom Guy", "Commander Shepard", "Marcus Fenix"], img: "green armored soldier sci-fi helmet" },
      { p: "Qual navegador foi criado pela Mozilla?", v: "Firefox", f: ["Chrome", "Edge", "Safari"], img: "Firefox browser fox fire logo" },
      { p: "Qual é o gênero do jogo Stardew Valley?", v: "Simulação de fazenda", f: ["RPG de ação", "FPS", "Battle Royale"], img: "pixel farm simulation crops harvest" },
      { p: "Qual estúdio criou o jogo Hades?", v: "Supergiant Games", f: ["Team Cherry", "FromSoftware", "Devolver Digital"], img: "underworld Greek mythology roguelike game" },
      { p: "Qual é o nome da IA maligna em Portal?", v: "GLaDOS", f: ["HAL 9000", "Skynet", "Cortana"], img: "robotic AI villain portal test chamber" },
      { p: "Qual é a moeda do jogo Fortnite?", v: "V-Bucks", f: ["Robux", "Minecoins", "Gil"], img: "virtual currency game coins digital" },
      { p: "Qual é o verdadeiro nome do Batman?", v: "Bruce Wayne", f: ["Clark Kent", "Tony Stark", "Peter Parker"], img: "dark knight cave bat signal city" },
      { p: "Qual console a Microsoft lançou em 2001?", v: "Xbox", f: ["PlayStation 2", "GameCube", "Dreamcast"], img: "Xbox original console controller 2001" },
      { p: "Qual anime tem o protagonista Monkey D. Luffy?", v: "One Piece", f: ["Dragon Ball", "Naruto", "Bleach"], img: "rubber pirate captain straw hat anime" },
      { p: "Qual é o nome do mapa mais famoso de Counter-Strike?", v: "Dust 2", f: ["Mirage", "Inferno", "Nuke"], img: "desert tactical shooter bomb site game" },
      { p: "Qual empresa criou o processador Ryzen?", v: "AMD", f: ["Intel", "Nvidia", "Qualcomm"], img: "AMD Ryzen CPU processor chip close-up" },
      { p: "Qual série de jogos tem o protagonista Nathan Drake?", v: "Uncharted", f: ["Tomb Raider", "Far Cry", "Assassin's Creed"], img: "treasure hunter adventure jungle ruins" },
      { p: "Qual é o jogo de estratégia em tempo real mais famoso?", v: "StarCraft", f: ["Age of Empires", "Warcraft", "Command & Conquer"], img: "sci-fi strategy game space battle RTS" }
    ],
    dificil: [
      { p: "Qual é o nome do vírus no anime Sword Art Online?", v: "NerveGear / Cardinal System", f: ["Matrix", "Skynet", "Deep Blue"], img: "virtual reality trapped game world anime" },
      { p: "Qual é a linguagem de programação usada para iOS?", v: "Swift", f: ["Kotlin", "Java", "Dart"], img: "Swift programming Apple iOS code" },
      { p: "Qual é o nome do modo competitivo de Dota 2?", v: "The International", f: ["World Championship", "Masters", "Legends"], img: "Dota 2 esports tournament stage" },
      { p: "Qual é a empresa por trás de ChatGPT?", v: "OpenAI", f: ["Google", "Meta", "Microsoft"], img: "artificial intelligence chatbot technology" },
      { p: "Qual jogo indie brasileiro ganhou destaque mundial em 2023?", v: "Dandara", f: ["Celeste", "Hollow Knight", "Dead Cells"], img: "Brazilian indie game colorful platformer" },
      { p: "Qual protocolo é usado para enviar emails?", v: "SMTP", f: ["HTTP", "FTP", "DNS"], img: "email server protocol sending messages" },
      { p: "Qual tipo de memória RAM é mais rápida?", v: "DDR5", f: ["DDR4", "DDR3", "GDDR6"], img: "DDR5 RAM memory stick computer" },
      { p: "Qual é o nome do robô assistente da Halo?", v: "Cortana", f: ["Siri", "Alexa", "343 Guilty Spark"], img: "holographic AI assistant blue light" },
      { p: "Qual manga é sobre alquimistas com braço mecânico?", v: "Fullmetal Alchemist", f: ["Attack on Titan", "Demon Slayer", "Vinland Saga"], img: "metal arm alchemy circle manga anime" },
      { p: "Qual é o nome da técnica de renderização que simula luz realista?", v: "Ray Tracing", f: ["Rasterização", "Wireframe", "Flat Shading"], img: "ray tracing realistic lighting reflection" },
      { p: "Qual foi o primeiro jogo da série The Elder Scrolls?", v: "Arena (1994)", f: ["Daggerfall", "Morrowind", "Oblivion"], img: "elder scrolls arena vintage RPG game" },
      { p: "Qual é o sistema operacional de código aberto mais usado?", v: "Linux", f: ["FreeBSD", "Haiku", "ReactOS"], img: "Linux Tux penguin open source code" },
      { p: "Qual personagem de Street Fighter é brasileiro?", v: "Blanka", f: ["Ryu", "Ken", "Dhalsim"], img: "green electrified fighter Brazilian jungle" },
      { p: "Qual formato de arquivo é usado para modelos 3D?", v: "OBJ / FBX", f: ["MP4", "PNG", "CSV"], img: "3D model wireframe rendering computer" },
      { p: "Qual foi o jogo mais vendido de todos os tempos?", v: "Minecraft", f: ["GTA V", "Tetris", "Wii Sports"], img: "Minecraft blocky world best selling game" }
    ],
    infernal: [
      { p: "Qual é o tamanho máximo de um pacote TCP?", v: "65.535 bytes", f: ["32.768 bytes", "128.000 bytes", "16.384 bytes"], img: "TCP packet data network structure" },
      { p: "Qual console tinha o processador Emotion Engine?", v: "PlayStation 2", f: ["Dreamcast", "GameCube", "Xbox"], img: "PlayStation 2 Emotion Engine chip" },
      { p: "Qual é o nome do criador de Metal Gear Solid?", v: "Hideo Kojima", f: ["Shigeru Miyamoto", "Hidetaka Miyazaki", "Toby Fox"], img: "cinematic stealth game director vision" },
      { p: "Qual é a complexidade do algoritmo Dijkstra com heap binário?", v: "O((V+E) log V)", f: ["O(V²)", "O(E log E)", "O(V·E)"], img: "graph algorithm shortest path nodes" },
      { p: "Qual disco rígido usa memória flash sem partes móveis?", v: "SSD", f: ["HDD", "SSHD", "Floppy"], img: "SSD solid state drive internal chips" },
      { p: "Qual é o nome do chip co-processador no Super Nintendo?", v: "Super FX", f: ["Mode 7", "Blast Processing", "HDMA"], img: "Super Nintendo chip retro gaming" },
      { p: "Qual é a diferença entre stack e heap na memória?", v: "Stack é LIFO estático, heap é dinâmico", f: ["São iguais", "Heap é LIFO", "Stack é para objetos"], img: "memory stack heap programming concept" },
      { p: "Qual é o nome do malware que criptografa arquivos e pede resgate?", v: "Ransomware", f: ["Trojan", "Worm", "Spyware"], img: "ransomware encrypted files lock screen" },
      { p: "Qual jogo japonês criou o conceito de JRPG?", v: "Dragon Quest (1986)", f: ["Final Fantasy (1987)", "Chrono Trigger (1995)", "Pokémon (1996)"], img: "classic JRPG turn-based battle pixel art" },
      { p: "Qual é o limite teórico de transistores por lei de Moore?", v: "Tamanho de átomos (~1nm)", f: ["10nm", "100nm", "0.1nm"], img: "Moore law transistor miniaturization chip" },
      { p: "Qual formato de compressão usa árvore de Huffman?", v: "ZIP / DEFLATE", f: ["RAR", "7z", "TAR"], img: "Huffman tree data compression algorithm" },
      { p: "Qual é o nome da rede neural que gera imagens a partir de texto?", v: "Diffusion Model", f: ["GAN", "RNN", "Transformer"], img: "AI diffusion model generating image" },
      { p: "Qual é o recorde de maior programa em assembly?", v: "RollerCoaster Tycoon (~99%)", f: ["Doom", "Quake", "Half-Life"], img: "theme park simulation game retro" },
      { p: "Qual é a frequência de atualização máxima de monitores gamer atuais?", v: "500 Hz", f: ["360 Hz", "240 Hz", "600 Hz"], img: "high refresh rate gaming monitor" },
      { p: "Qual distribuição Linux é baseada no Arch?", v: "Manjaro", f: ["Ubuntu", "Fedora", "Debian"], img: "Arch Linux terminal command line" }
    ]
  },

  esportes: {
    facil: [
      { p: "Qual esporte usa luvas e um ringue?", v: "Boxe", f: ["Judô", "Karatê", "Luta livre"], img: "boxing ring gloves fighting sport" },
      { p: "Qual é a cor da bola de tênis?", v: "Amarelo-verde", f: ["Branco", "Laranja", "Vermelho"], img: "tennis ball yellow green close-up" },
      { p: "Qual país é famoso pelo beisebol?", v: "EUA", f: ["Índia", "Brasil", "Alemanha"], img: "baseball game American stadium" },
      { p: "Quantos jogadores tem um time de basquete em quadra?", v: "5 jogadores", f: ["6 jogadores", "7 jogadores", "4 jogadores"], img: "basketball court five players game" },
      { p: "Qual esporte olímpico usa arco e flecha?", v: "Tiro com arco", f: ["Esgrima", "Tiro esportivo", "Dardos"], img: "archery bow arrow target Olympic" },
      { p: "Qual esporte de inverno desliza no gelo com lâminas?", v: "Patinação artística", f: ["Curling", "Bobsled", "Luge"], img: "figure skating ice performance" },
      { p: "Qual é o esporte mais praticado nas praias do Brasil?", v: "Futevôlei / vôlei de praia", f: ["Surfe", "Futebol", "Natação"], img: "beach volleyball sand court ocean" },
      { p: "Qual animal é associado ao esporte de corrida?", v: "Cavalo", f: ["Cachorro", "Gato", "Camelo"], img: "horse racing jockey track speed" },
      { p: "Qual é o nome do esporte que usa skis na neve?", v: "Esqui", f: ["Snowboard", "Patinação", "Bobsled"], img: "skiing snow mountain slope winter" },
      { p: "Qual bola é oval no rugby?", v: "Bola de rugby", f: ["Bola de futebol", "Bola de basquete", "Bola de vôlei"], img: "rugby oval ball on green grass" },
      { p: "Quantos tempos tem um jogo de futebol?", v: "2 tempos", f: ["3 tempos", "4 tempos", "1 tempo"], img: "soccer match halftime football" },
      { p: "Qual esporte usa raquete e mesa?", v: "Tênis de mesa (ping-pong)", f: ["Badminton", "Squash", "Padel"], img: "table tennis ping pong paddle ball" },
      { p: "Qual modalidade de natação é a mais rápida?", v: "Nado crawl (livre)", f: ["Borboleta", "Costas", "Peito"], img: "freestyle crawl swimming fast pool" },
      { p: "Qual esporte usa um taco para rebater uma bola no golfe?", v: "Golfe", f: ["Críquete", "Hóquei", "Polo"], img: "golf club swing ball tee course" },
      { p: "Qual é o prêmio dado ao melhor jogador de futebol?", v: "Bola de Ouro", f: ["FIFA The Best", "Chuteira de Ouro", "Luva de Ouro"], img: "Ballon dOr trophy golden ball" }
    ],
    medio: [
      { p: "Qual seleção ganhou a primeira Copa do Mundo (1930)?", v: "Uruguai", f: ["Brasil", "Argentina", "Itália"], img: "Uruguay 1930 World Cup first champions" },
      { p: "Qual esporte combina natação, ciclismo e corrida?", v: "Triathlon", f: ["Decathlon", "Pentatlo", "Biatlo"], img: "triathlon swim bike run transition" },
      { p: "Qual tenista brasileira foi número 1 do mundo?", v: "Maria Esther Bueno", f: ["Guga", "Gustavo Kuerten", "Fernando Meligeni"], img: "Brazilian tennis champion historical" },
      { p: "Qual é o nome do estádio do Flamengo?", v: "Maracanã", f: ["Morumbi", "Beira-Rio", "Arena Corinthians"], img: "Maracana stadium Rio de Janeiro" },
      { p: "Qual esporte de luta usa o tatame?", v: "Judô", f: ["Boxe", "MMA", "Luta greco-romana"], img: "judo tatami mat martial arts throw" },
      { p: "Qual piloto brasileiro ganhou 3 títulos de F1?", v: "Ayrton Senna", f: ["Nelson Piquet", "Emerson Fittipaldi", "Rubens Barrichello"], img: "Ayrton Senna racing car Brazilian flag" },
      { p: "Qual esporte olímpico usa cavalos?", v: "Hipismo", f: ["Polo", "Corrida de cavalos", "Polo aquático"], img: "equestrian show jumping horse Olympics" },
      { p: "Qual jogador de basquete usava o número 23?", v: "Michael Jordan", f: ["Kobe Bryant", "LeBron James", "Magic Johnson"], img: "basketball player number 23 slam dunk" },
      { p: "Qual país domina o rugby mundialmente?", v: "Nova Zelândia (All Blacks)", f: ["Inglaterra", "Austrália", "África do Sul"], img: "All Blacks rugby haka New Zealand" },
      { p: "Qual é o nome da competição de vela mais famosa?", v: "America's Cup", f: ["Volvo Ocean Race", "Copa Vendée Globe", "Regata Sydney-Hobart"], img: "Americas Cup sailing yacht race ocean" },
      { p: "Qual esporte usa disco (frisbee) competitivamente?", v: "Ultimate Frisbee", f: ["Golfe de disco", "Polo", "Lacrosse"], img: "ultimate frisbee disc throw competition" },
      { p: "Qual ginasta brasileiro ganhou medalha olímpica?", v: "Arthur Zanetti", f: ["Diego Hypólito", "Daiane dos Santos", "Jade Barbosa"], img: "gymnastics rings Olympic medal" },
      { p: "Qual é o nome da liga profissional de futebol americano?", v: "NFL", f: ["NBA", "MLB", "MLS"], img: "NFL American football helmet stadium" },
      { p: "Qual é a distância dos 'tiros curtos' no atletismo?", v: "100m e 200m", f: ["400m e 800m", "50m e 100m", "110m e 200m"], img: "sprint starting blocks athletics track" },
      { p: "Qual país sediará a Copa do Mundo de 2026?", v: "EUA, Canadá e México", f: ["Arábia Saudita", "Austrália", "Marrocos"], img: "2026 World Cup North America stadiums" }
    ],
    dificil: [
      { p: "Qual é o recorde mundial feminino dos 100m rasos?", v: "10,49s (Florence Griffith-Joyner)", f: ["10,65s", "10,72s", "10,54s"], img: "female sprinter world record track" },
      { p: "Qual esporte olímpico combina esqui e tiro?", v: "Biatlo", f: ["Pentatlo moderno", "Combinado nórdico", "Esqui cross-country"], img: "biathlon skiing shooting winter sport" },
      { p: "Qual jogador argentino é apelidado de 'El Pibe de Oro'?", v: "Maradona", f: ["Messi", "Di Stéfano", "Batistuta"], img: "Argentine football legend golden boy" },
      { p: "Qual é o nome da formação 4-3-3 no futebol?", v: "4 defensores, 3 meias, 3 atacantes", f: ["4-4-2 variante", "3-5-2 adaptado", "5-3-2"], img: "football tactical formation 4-3-3 diagram" },
      { p: "Qual país ganhou mais medalhas olímpicas na história?", v: "EUA", f: ["Rússia/URSS", "China", "Alemanha"], img: "Olympic medals collection gold silver bronze" },
      { p: "Qual corrida automobilística tem o circuito mais perigoso?", v: "Isle of Man TT (motos)", f: ["Dakar", "Le Mans", "Fórmula 1"], img: "Isle of Man TT dangerous motorcycle race" },
      { p: "Qual é o peso de uma bola de futebol oficial?", v: "410-450 gramas", f: ["350-380g", "500-550g", "250-300g"], img: "official football ball FIFA weight" },
      { p: "Qual atleta jamaicano detém 8 ouros olímpicos?", v: "Usain Bolt", f: ["Asafa Powell", "Yohan Blake", "Shelly-Ann Fraser-Pryce"], img: "Jamaican sprinter Olympic champion pose" },
      { p: "Qual é a distância de um 'half-marathon'?", v: "21,0975 km", f: ["25 km", "20 km", "15 km"], img: "half marathon runners city course" },
      { p: "Qual esporte de inverno usa uma vassoura e uma pedra?", v: "Curling", f: ["Hóquei", "Bobsled", "Skeleton"], img: "curling stone broom ice sliding" },
      { p: "Qual foi a maior goleada da seleção brasileira?", v: "14x0 (vs Nicarágua, 2012)", f: ["10x0", "12x0", "7x0"], img: "Brazil national team celebrating goal" },
      { p: "Qual surfista brasileiro foi campeão mundial?", v: "Gabriel Medina", f: ["Filipe Toledo", "Adriano de Souza", "Ítalo Ferreira"], img: "Brazilian surfer world champion waves" },
      { p: "Qual é o nome do torneio de rugby entre países do hemisfério sul?", v: "Rugby Championship", f: ["Six Nations", "World Rugby Cup", "Super Rugby"], img: "rugby championship southern hemisphere" },
      { p: "Qual boxeador tem o recorde de invencibilidade de 50-0?", v: "Floyd Mayweather Jr.", f: ["Rocky Marciano", "Muhammad Ali", "Mike Tyson"], img: "undefeated boxer championship belt" },
      { p: "Qual é o peso máximo no levantamento de peso olímpico (categoria)?", v: "+109 kg (superpesado)", f: ["+120 kg", "+100 kg", "+90 kg"], img: "Olympic weightlifting super heavyweight" }
    ],
    infernal: [
      { p: "Qual é a velocidade máxima de uma bola de golfe após o drive?", v: "~320 km/h", f: ["~250 km/h", "~400 km/h", "~180 km/h"], img: "golf drive ball speed launch monitor" },
      { p: "Qual é o recorde de gols em uma única Copa do Mundo?", v: "13 gols (Just Fontaine, 1958)", f: ["14 gols", "11 gols", "15 gols"], img: "World Cup top scorer historical record" },
      { p: "Qual é a altitude máxima permitida para campos de futebol pela FIFA?", v: "2.500m (com exceções)", f: ["3.000m", "2.000m", "4.000m"], img: "high altitude football stadium mountains" },
      { p: "Qual é o diâmetro oficial de uma cesta de basquete?", v: "45,72 cm (18 polegadas)", f: ["50 cm", "40 cm", "55 cm"], img: "basketball hoop rim exact diameter" },
      { p: "Qual atleta ganhou ouro nos 200m e 400m rasos na mesma Olimpíada?", v: "Michael Johnson (1996)", f: ["Usain Bolt", "Carl Lewis", "Jesse Owens"], img: "sprinter gold shoes Olympic double gold" },
      { p: "Qual é a velocidade máxima registrada de uma bola de futebol?", v: "~211 km/h (Ronny Heberson)", f: ["~190 km/h", "~230 km/h", "~170 km/h"], img: "powerful soccer free kick speed" },
      { p: "Qual é o nome da técnica de natação mais antiga?", v: "Nado de peito (breaststroke)", f: ["Crawl", "Costas", "Borboleta"], img: "breaststroke swimming technique historical" },
      { p: "Qual é o recorde de pontos em um único jogo da NBA?", v: "100 pontos (Wilt Chamberlain)", f: ["81 pontos", "73 pontos", "92 pontos"], img: "basketball scoring record historical game" },
      { p: "Qual esporte tem o troféu chamado 'Stanley Cup'?", v: "Hóquei no gelo (NHL)", f: ["Basquete (NBA)", "Futebol americano (NFL)", "Beisebol (MLB)"], img: "Stanley Cup ice hockey trophy" },
      { p: "Qual é o tempo mínimo para um nocaute técnico no boxe?", v: "Não há tempo mínimo", f: ["10 segundos", "5 segundos", "3 rounds"], img: "boxing TKO knockout referee count" },
      { p: "Qual jogador de críquete tem mais séculos (centuries)?", v: "Sachin Tendulkar (100)", f: ["Ricky Ponting", "Virat Kohli", "Jacques Kallis"], img: "cricket batsman century celebration" },
      { p: "Qual é o nome da técnica de salto no vôlei inventada por brasileiros?", v: "Jornada nas estrelas", f: ["Virada de bola", "Ataque tempo", "Manchete de costas"], img: "volleyball jump serve technique Brazilian" },
      { p: "Qual foi o primeiro esporte a ser televisionado?", v: "Beisebol (1939)", f: ["Boxe", "Futebol", "Tênis"], img: "first televised sport baseball 1939" },
      { p: "Qual é a pontuação máxima possível em um frame de boliche?", v: "30 pontos (3 strikes seguidos)", f: ["20 pontos", "10 pontos", "40 pontos"], img: "bowling perfect frame triple strike" },
      { p: "Qual é o recorde de velocidade no ciclismo em pista?", v: "~280 km/h (atrás de veículo)", f: ["~200 km/h", "~320 km/h", "~150 km/h"], img: "cycling speed record velodrome track" }
    ]
  },

  musica: {
    facil: [
      { p: "Qual instrumento tem formato de violão mas é menor?", v: "Ukulele", f: ["Cavaquinho", "Banjo", "Bandolim"], img: "ukulele small guitar Hawaiian instrument" },
      { p: "Qual cantor brasileiro é conhecido como 'Rei'?", v: "Roberto Carlos", f: ["Caetano Veloso", "Gilberto Gil", "Tim Maia"], img: "Brazilian king of music vintage stage" },
      { p: "Qual instrumento se toca com baquetas?", v: "Bateria", f: ["Guitarra", "Piano", "Violino"], img: "drumsticks hitting drum snare cymbal" },
      { p: "Quantas notas musicais existem na escala básica?", v: "7 notas", f: ["5 notas", "8 notas", "12 notas"], img: "seven musical notes do re mi scale" },
      { p: "Qual cantor pop é chamado de 'Rei do Pop'?", v: "Michael Jackson", f: ["Prince", "Justin Timberlake", "Bruno Mars"], img: "pop star iconic dance moonwalk" },
      { p: "Qual instrumento de sopro é feito de metal e tem pistões?", v: "Trompete", f: ["Flauta", "Oboé", "Clarinete"], img: "trumpet brass instrument close-up" },
      { p: "Qual banda brasileira cantou 'Evidências'?", v: "Chitãozinho & Xororó", f: ["Zezé Di Camargo & Luciano", "Leandro & Leonardo", "Bruno & Marrone"], img: "Brazilian country duo sertanejo stage" },
      { p: "Qual instrumento é tocado com arco?", v: "Violino", f: ["Violão", "Guitarra", "Harpa"], img: "violin bow strings classical music" },
      { p: "Qual ritmo tem origem afro-brasileira e usa atabaques?", v: "Samba / Candomblé", f: ["Rock", "Jazz", "Blues"], img: "atabaque drums Brazilian Afro percussion" },
      { p: "Qual cantora americana é conhecida como 'Queen Bey'?", v: "Beyoncé", f: ["Rihanna", "Taylor Swift", "Ariana Grande"], img: "powerful female pop singer stage performance" },
      { p: "Qual instrumento japonês tem cordas e é tocado horizontalmente?", v: "Koto", f: ["Shamisen", "Shakuhachi", "Taiko"], img: "koto Japanese string instrument traditional" },
      { p: "Qual é o nome da pausa musical que vale 1 tempo?", v: "Pausa de semínima", f: ["Pausa de mínima", "Pausa de colcheia", "Pausa de semibreve"], img: "quarter rest musical notation" },
      { p: "Qual cantor brasileiro cantou 'Garota de Ipanema'?", v: "Tom Jobim / Vinícius", f: ["Caetano Veloso", "Chico Buarque", "João Gilberto"], img: "Girl from Ipanema bossa nova Rio beach" },
      { p: "Qual grupo musical usava máscaras e macacões?", v: "Slipknot", f: ["KISS", "Gwar", "Mushroomhead"], img: "masked heavy metal band stage concert" },
      { p: "Qual tipo de música é cantada em ópera?", v: "Música lírica/clássica", f: ["Rock", "Pop", "Sertanejo"], img: "opera singer dramatic classical stage" }
    ],
    medio: [
      { p: "Qual é o nome do período musical entre 1600 e 1750?", v: "Barroco", f: ["Clássico", "Romântico", "Renascimento"], img: "Baroque music era ornate harpsichord" },
      { p: "Qual instrumento eletrônico foi inventado nos anos 1920?", v: "Theremin", f: ["Sintetizador", "Sampler", "Drum machine"], img: "theremin electronic instrument without touch" },
      { p: "Qual banda lançou o álbum 'Nevermind'?", v: "Nirvana", f: ["Pearl Jam", "Soundgarden", "Alice in Chains"], img: "grunge rock album baby underwater" },
      { p: "Qual é o nome da família de instrumentos de corda com arco?", v: "Cordas friccionadas", f: ["Cordas dedilhadas", "Sopros", "Percussão"], img: "string quartet violin viola cello bass" },
      { p: "Qual cantor brasileiro é ícone do Tropicalismo?", v: "Caetano Veloso", f: ["Roberto Carlos", "Elis Regina", "Raul Seixas"], img: "Tropicalia movement Brazilian music colorful" },
      { p: "Qual efeito sonoro cria eco na música?", v: "Delay / Reverb", f: ["Distortion", "Chorus", "Flanger"], img: "reverb echo sound waves room acoustics" },
      { p: "Qual instrumento africano é uma espécie de piano de polegar?", v: "Kalimba / Mbira", f: ["Djembê", "Balafon", "Kora"], img: "kalimba thumb piano African instrument" },
      { p: "Qual é o tom padrão usado para afinar instrumentos?", v: "Lá (A4 = 440 Hz)", f: ["Dó (C4)", "Sol (G4)", "Mi (E4)"], img: "tuning fork A440 concert pitch" },
      { p: "Qual rapper brasileiro é conhecido como 'Racionais'?", v: "Mano Brown (Racionais MC's)", f: ["Emicida", "Criolo", "Djonga"], img: "Brazilian rap hip hop stage concert" },
      { p: "Qual instrumento de sopro duplo é conhecido pelo som melancólico?", v: "Oboé", f: ["Fagote", "Clarinete", "Flauta"], img: "oboe double reed woodwind close-up" },
      { p: "Qual tipo de guitarra não usa amplificador?", v: "Guitarra acústica / violão", f: ["Guitarra elétrica", "Guitarra semi-acústica", "Bass guitar"], img: "acoustic guitar unplugged wooden body" },
      { p: "Qual sistema de notação usa 'Dó, Ré, Mi'?", v: "Sistema de solfejo", f: ["Tablatura", "Cifra", "Notação numérica"], img: "solfege do re mi fa sol la si" },
      { p: "Qual banda de rock progressivo gravou 'Wish You Were Here'?", v: "Pink Floyd", f: ["Yes", "Genesis", "Rush"], img: "album cover two men handshake fire" },
      { p: "Qual é o nome da técnica de cantar sem palavras?", v: "Vocalise", f: ["Acappella", "Beatbox", "Scat"], img: "vocalist singing without words technique" },
      { p: "Qual compositor russo escreveu 'A Sagração da Primavera'?", v: "Igor Stravinsky", f: ["Rachmaninoff", "Prokofiev", "Shostakovich"], img: "Rite of Spring ballet modern music" }
    ],
    dificil: [
      { p: "Qual instrumento africano de cordas tem 21 cordas?", v: "Kora", f: ["Kalimba", "Ngoni", "Nyatiti"], img: "kora West African harp instrument" },
      { p: "Qual é o nome da escala com 5 notas?", v: "Pentatônica", f: ["Cromática", "Diatônica", "Hexatônica"], img: "pentatonic scale five notes piano" },
      { p: "Qual artista vendeu mais discos na história?", v: "Elvis Presley", f: ["The Beatles", "Michael Jackson", "Madonna"], img: "vinyl records best selling artist ever" },
      { p: "Qual compositor ficou famoso pelas valsas vienenses?", v: "Johann Strauss II", f: ["Chopin", "Liszt", "Brahms"], img: "Viennese waltz ballroom dancing orchestra" },
      { p: "Qual é o nome do instrumento indiano de percussão?", v: "Tabla", f: ["Sitar", "Sarod", "Veena"], img: "tabla Indian percussion drums pair" },
      { p: "Qual gênero musical combina elementos de rock e hip-hop?", v: "Nu Metal / Rap Rock", f: ["Grunge", "Punk Rock", "Indie Rock"], img: "nu metal rock hip hop fusion concert" },
      { p: "Qual é a diferença entre tempo e compasso?", v: "Tempo é velocidade, compasso é divisão rítmica", f: ["São iguais", "Tempo é ritmo", "Compasso é velocidade"], img: "musical time signature tempo marking" },
      { p: "Qual músico brasileiro revolucionou a guitarra baiana?", v: "Pepeu Gomes", f: ["Armandinho", "Moraes Moreira", "Baby do Brasil"], img: "Brazilian guitarist Bahia electric guitar" },
      { p: "Qual técnica vocal consiste em cantar duas notas ao mesmo tempo?", v: "Canto difônico (overtone singing)", f: ["Falsete", "Yodel", "Vibrato"], img: "overtone singing throat vocal technique" },
      { p: "Qual é o instrumento mais grave da orquestra?", v: "Contrabaixo / Tuba", f: ["Violoncelo", "Fagote", "Trombone"], img: "double bass contrabass orchestra low" },
      { p: "Qual compositor criou a forma 'fuga' mais complexa?", v: "J.S. Bach", f: ["Handel", "Vivaldi", "Telemann"], img: "Bach fugue manuscript musical notation" },
      { p: "Qual é o nome do sistema de 12 notas iguais usado no piano?", v: "Temperamento igual", f: ["Afinação justa", "Pitagórica", "Mesotônico"], img: "equal temperament piano tuning system" },
      { p: "Qual movimento musical brasileiro surgiu em Recife nos anos 90?", v: "Manguebeat", f: ["Tropicália", "Bossa Nova", "Jovem Guarda"], img: "Manguebeat Recife music crab mangrove" },
      { p: "Qual efeito na guitarra cria um som 'wah-wah'?", v: "Pedal Wah-wah", f: ["Pedal de distorção", "Pedal chorus", "Pedal delay"], img: "wah-wah guitar effect pedal" },
      { p: "Qual DJ brasileiro se apresentou no Tomorrowland?", v: "Alok", f: ["Vintage Culture", "Cat Dealers", "KVSH"], img: "Brazilian DJ electronic music festival stage" }
    ],
    infernal: [
      { p: "Qual é o nome da notação rítmica indiana?", v: "Tala", f: ["Raga", "Shruti", "Gharana"], img: "Indian tala rhythm notation tabla" },
      { p: "Qual é a razão de frequência de uma oitava?", v: "2:1", f: ["3:2", "4:3", "5:4"], img: "octave frequency ratio wave physics" },
      { p: "Qual instrumento medieval precedeu o piano?", v: "Clavicórdio", f: ["Cravo", "Espineta", "Virginal"], img: "clavichord medieval keyboard instrument" },
      { p: "Qual compositor serialista usou 'total serialism'?", v: "Pierre Boulez", f: ["Karlheinz Stockhausen", "Milton Babbitt", "Luigi Nono"], img: "total serialism avant-garde composition" },
      { p: "Qual é a afinação alternativa mais comum na guitarra?", v: "Drop D", f: ["Open G", "DADGAD", "Open E"], img: "guitar drop D tuning alternate" },
      { p: "Qual compositor húngaro coletou músicas folclóricas?", v: "Béla Bartók", f: ["Zoltán Kodály", "Franz Liszt", "György Ligeti"], img: "Hungarian folk music collection ethnomusicology" },
      { p: "Qual é o nome do dispositivo que grava múltiplas faixas simultaneamente?", v: "Gravador multipista (multitrack)", f: ["Mixer", "Compressor", "Equalizador"], img: "multitrack recording studio mixer" },
      { p: "Qual é o nome do fenômeno acústico em salas circulares?", v: "Galeria dos sussurros (whispering gallery)", f: ["Reverberação", "Eco", "Difração"], img: "whispering gallery dome acoustic phenomenon" },
      { p: "Qual é a velocidade mais lenta indicada em partitura?", v: "Larghissimo", f: ["Largo", "Adagio", "Grave"], img: "tempo marking larghissimo slowest music" },
      { p: "Qual é o nome da técnica de guitarra que usa o dedo batendo na corda?", v: "Tapping", f: ["Slapping", "Picking", "Strumming"], img: "guitar tapping technique fretboard" },
      { p: "Qual é o ciclo de quintas e para que serve?", v: "Organiza tonalidades por quintas justas", f: ["Ordena notas por oitavas", "Define ritmos", "Classifica instrumentos"], img: "circle of fifths music theory chart" },
      { p: "Qual compositora escreveu 'Bachianas Brasileiras'?", v: "Villa-Lobos (compositor)", f: ["Carlos Gomes", "Camargo Guarnieri", "Radamés Gnattali"], img: "Villa-Lobos Bachianas Brasileiras classical" },
      { p: "Qual sintetizador analógico é considerado o mais lendário?", v: "Minimoog Model D", f: ["Roland Juno-60", "ARP 2600", "Sequential Prophet-5"], img: "Minimoog Model D analog synthesizer" },
      { p: "Qual é o nome da técnica de breathing control usada por cantores de ópera?", v: "Appoggio", f: ["Bel canto", "Coloratura", "Portamento"], img: "opera breathing technique diaphragm" },
      { p: "Qual compositor minimalista escreveu 'Music for 18 Musicians'?", v: "Steve Reich", f: ["Philip Glass", "Terry Riley", "John Adams"], img: "minimalist music repetitive patterns" }
    ]
  },

  filmes: {
    facil: [
      { p: "Qual é o nome do leão em 'O Rei Leão'?", v: "Simba", f: ["Mufasa", "Scar", "Nala"], img: "lion cub on pride rock sunset" },
      { p: "Qual filme tem um peixe que esquece tudo?", v: "Procurando Dory", f: ["Procurando Nemo", "Moana", "A Pequena Sereia"], img: "blue fish forgetful underwater coral" },
      { p: "Qual herói usa uma capa vermelha e voa?", v: "Superman", f: ["Batman", "Flash", "Aquaman"], img: "flying superhero red cape blue sky" },
      { p: "Qual filme de animação tem um rato que cozinha?", v: "Ratatouille", f: ["Stuart Little", "Flushed Away", "Fievel"], img: "rat cooking French restaurant kitchen" },
      { p: "Qual filme tem um menino bruxo com cicatriz?", v: "Harry Potter", f: ["Percy Jackson", "Crônicas de Nárnia", "Senhor dos Anéis"], img: "wizard boy school castle magical" },
      { p: "Qual princesa tem cabelo muito longo?", v: "Rapunzel", f: ["Cinderela", "Bela", "Ariel"], img: "princess very long golden hair tower" },
      { p: "Qual filme tem carros que correm muito rápido?", v: "Velozes e Furiosos", f: ["Need for Speed", "Cars", "Rush"], img: "fast cars street racing neon night" },
      { p: "Qual filme tem um boneco de neve que fala?", v: "Frozen", f: ["A Era do Gelo", "Happy Feet", "Rudolph"], img: "talking snowman magical winter cute" },
      { p: "Qual super-herói tem teia e sobe em prédios?", v: "Homem-Aranha", f: ["Batman", "Demolidor", "Venom"], img: "web-slinging hero climbing tall building" },
      { p: "Qual filme tem aliens verdes com antenas?", v: "Toy Story (aliens)", f: ["E.T.", "MIB", "Mars Attacks"], img: "green aliens with antennas claw machine" },
      { p: "Qual filme mostra a vida no fundo do mar?", v: "Procurando Nemo", f: ["Moana", "A Pequena Sereia", "Atlantis"], img: "underwater ocean fish coral reef colorful" },
      { p: "Qual vilão tem luvas com garras afiadas?", v: "Freddy Krueger", f: ["Jason", "Michael Myers", "Chucky"], img: "nightmare villain razor glove horror" },
      { p: "Qual é o nome do robô amigo no filme 'Wall-E'?", v: "Wall-E", f: ["Eve", "Baymax", "R2-D2"], img: "small robot cleaning Earth wasteland" },
      { p: "Qual filme tem uma família de super-heróis?", v: "Os Incríveis", f: ["Quarteto Fantástico", "X-Men", "Liga da Justiça"], img: "superhero family animated action movie" },
      { p: "Qual animal é o protagonista de 'Madagascar'?", v: "Leão (Alex)", f: ["Zebra", "Girafa", "Hipopótamo"], img: "zoo animals adventure tropical island" }
    ],
    medio: [
      { p: "Qual diretor é famoso por filmes de terror psicológico?", v: "Jordan Peele", f: ["James Wan", "Ari Aster", "Mike Flanagan"], img: "psychological horror dark sunken place" },
      { p: "Qual ator interpretou Jack em 'Titanic'?", v: "Leonardo DiCaprio", f: ["Brad Pitt", "Matt Damon", "Tom Hanks"], img: "romantic ship ocean 1997 movie" },
      { p: "Qual série tem zumbis no apocalipse?", v: "The Walking Dead", f: ["Stranger Things", "Lost", "The 100"], img: "zombie apocalypse city destroyed horror" },
      { p: "Qual filme ganhou o Oscar de Melhor Filme em 2023?", v: "Tudo em Todo Lugar ao Mesmo Tempo", f: ["Top Gun: Maverick", "Avatar 2", "Os Banshees de Inisherin"], img: "multiverse movie Oscar award winner" },
      { p: "Qual ator é famoso por seus filmes de ação nos anos 80?", v: "Arnold Schwarzenegger", f: ["Sylvester Stallone", "Bruce Willis", "Chuck Norris"], img: "1980s action movie muscle hero" },
      { p: "Qual série tem uma escola para espiões adolescentes?", v: "Alex Rider / Spy Kids", f: ["Stranger Things", "Umbrella Academy", "The 100"], img: "teenage spy school adventure action" },
      { p: "Qual filme de Pixar mostra emoções dentro da mente?", v: "Divertida Mente (Inside Out)", f: ["Soul", "Viva (Coco)", "Onward"], img: "emotions inside mind colorful characters" },
      { p: "Qual atriz interpretou a Viúva Negra na Marvel?", v: "Scarlett Johansson", f: ["Gal Gadot", "Brie Larson", "Elizabeth Olsen"], img: "spy heroine action movie fight scene" },
      { p: "Qual filme tem a frase 'Eu vejo gente morta'?", v: "O Sexto Sentido", f: ["O Iluminado", "Os Outros", "Invocação do Mal"], img: "supernatural child ghost mystery thriller" },
      { p: "Qual diretor brasileiro dirigiu 'Cidade de Deus'?", v: "Fernando Meirelles", f: ["Walter Salles", "José Padilha", "Kleber Mendonça"], img: "Brazilian favela movie intense dramatic" },
      { p: "Qual filme de animação japonesa mostra espíritos em uma casa de banho?", v: "A Viagem de Chihiro", f: ["Princesa Mononoke", "Meu Vizinho Totoro", "Ponyo"], img: "Japanese bathhouse spirits magical anime" },
      { p: "Qual ator interpretou o Thanos na Marvel?", v: "Josh Brolin", f: ["Idris Elba", "Karl Urban", "Dave Bautista"], img: "purple giant villain cosmic power stones" },
      { p: "Qual série mostra a vida de Pablo Escobar?", v: "Narcos", f: ["Breaking Bad", "Ozark", "Power"], img: "Colombian drug lord crime drama" },
      { p: "Qual filme de terror tem uma boneca possuída?", v: "Annabelle", f: ["Chucky", "Saw", "A Maldição da Chorona"], img: "possessed doll horror creepy vintage" },
      { p: "Qual ator interpreta o John Wick?", v: "Keanu Reeves", f: ["Jason Statham", "Tom Cruise", "Liam Neeson"], img: "assassin action movie dark suit weapons" }
    ],
    dificil: [
      { p: "Qual diretor iraniano ganhou o Oscar com 'A Separação'?", v: "Asghar Farhadi", f: ["Abbas Kiarostami", "Jafar Panahi", "Majid Majidi"], img: "Iranian cinema dramatic family conflict" },
      { p: "Qual é o filme mais caro já produzido?", v: "Piratas do Caribe: Navegando em Águas Misteriosas", f: ["Vingadores: Ultimato", "Avatar", "Star Wars: O Despertar da Força"], img: "most expensive movie production set" },
      { p: "Qual técnica cinematográfica usa uma única tomada contínua?", v: "Plano-sequência", f: ["Montagem paralela", "Jump cut", "Slow motion"], img: "long take continuous shot cinema" },
      { p: "Qual ator ganhou Oscars consecutivos de Melhor Ator?", v: "Tom Hanks (1993, 1994)", f: ["Daniel Day-Lewis", "Jack Nicholson", "Spencer Tracy"], img: "consecutive Oscar wins Best Actor" },
      { p: "Qual filme distópico se passa em um trem que nunca para?", v: "Snowpiercer", f: ["Mad Max", "The Road", "Children of Men"], img: "endless train post-apocalyptic snow" },
      { p: "Qual diretor coreano ganhou a Palma de Ouro e o Oscar?", v: "Bong Joon-ho", f: ["Park Chan-wook", "Kim Ki-duk", "Lee Chang-dong"], img: "Korean cinema director award-winning" },
      { p: "Qual animação da Disney foi a primeira longa-metragem?", v: "Branca de Neve (1937)", f: ["Fantasia (1940)", "Pinóquio (1940)", "Dumbo (1941)"], img: "Snow White Disney first animation classic" },
      { p: "Qual cinematógrafo é famoso por filmar 'Blade Runner 2049'?", v: "Roger Deakins", f: ["Emmanuel Lubezki", "Janusz Kamiński", "Robert Richardson"], img: "Blade Runner 2049 cinematography neon" },
      { p: "Qual é o nome da técnica de edição inventada por Eisenstein?", v: "Montagem soviética", f: ["Jump cut", "Cross cutting", "Match cut"], img: "Soviet montage editing film theory" },
      { p: "Qual filme de Wes Anderson tem um hotel rosa?", v: "O Grande Hotel Budapeste", f: ["A Família Tenenbaum", "Moonrise Kingdom", "Isle of Dogs"], img: "pink grand hotel symmetrical pastel" },
      { p: "Qual atriz ganhou mais indicações ao Oscar?", v: "Meryl Streep (21)", f: ["Katharine Hepburn", "Judi Dench", "Cate Blanchett"], img: "Oscar nominations record actress Hollywood" },
      { p: "Qual filme de ficção científica tem replicantes?", v: "Blade Runner", f: ["Ex Machina", "A.I.", "Ghost in the Shell"], img: "replicant sci-fi neon rain cityscape" },
      { p: "Qual série tem a frase 'Winter is coming'?", v: "Game of Thrones", f: ["The Witcher", "Vikings", "Lord of the Rings"], img: "icy wall fortress medieval winter" },
      { p: "Qual compositor criou a trilha de Star Wars?", v: "John Williams", f: ["Hans Zimmer", "Howard Shore", "Danny Elfman"], img: "orchestra recording movie soundtrack stage" },
      { p: "Qual é o filme noir mais influente?", v: "Double Indemnity (1944)", f: ["Casablanca", "Citizen Kane", "The Maltese Falcon"], img: "film noir shadow venetian blinds mystery" }
    ],
    infernal: [
      { p: "Qual é o nome da técnica de som que usa a diferença entre canais?", v: "Stereo panning", f: ["Surround sound", "Dolby Atmos", "Binaural audio"], img: "stereo sound mixing console channels" },
      { p: "Qual filme foi o primeiro a usar sincronização de som Dolby?", v: "A Clockwork Orange (Dolby Noise Reduction)", f: ["Star Wars", "Jaws", "The Exorcist"], img: "Dolby sound vintage cinema technology" },
      { p: "Qual diretor tem a filmografia mais longa com um mesmo ator?", v: "Martin Scorsese & Robert De Niro", f: ["Tim Burton & Johnny Depp", "Spielberg & Hanks", "Nolan & Cillian Murphy"], img: "director actor duo collaboration legendary" },
      { p: "Qual formato de filme IMAX usa película de 70mm?", v: "IMAX 15/70", f: ["IMAX Digital", "IMAX 35mm", "IMAX Laser"], img: "IMAX 70mm film reel giant camera" },
      { p: "Qual filme independente de mumblecore custou apenas US$7.000?", v: "Funny Ha Ha (2002)", f: ["The Puffy Chair", "Hannah Takes the Stairs", "Baghead"], img: "low budget indie film mumblecore" },
      { p: "Qual lente cinematográfica cria o efeito 'anamórfico'?", v: "Lente anamórfica", f: ["Lente grande-angular", "Lente teleobjetiva", "Lente macro"], img: "anamorphic lens flare widescreen cinema" },
      { p: "Qual foi o primeiro filme colorido com Technicolor completo?", v: "Becky Sharp (1935)", f: ["O Mágico de Oz", "E o Vento Levou", "Fantasia"], img: "Technicolor first full color film 1935" },
      { p: "Qual editor ganhou mais Oscars de Melhor Montagem?", v: "Michael Kahn (3 Oscars)", f: ["Thelma Schoonmaker", "Walter Murch", "Anne V. Coates"], img: "film editing Oscar Academy Award" },
      { p: "Qual é o nome da regra dos terços na composição cinematográfica?", v: "Rule of thirds", f: ["Golden ratio", "Fibonacci spiral", "Leading lines"], img: "rule of thirds grid cinematography" },
      { p: "Qual filme usa o efeito 'Zolly' (Vertigo effect)?", v: "Tubarão (Jaws, 1975)", f: ["Vertigo", "Goodfellas", "The Lord of the Rings"], img: "dolly zoom zolly effect beach scene" },
      { p: "Qual é a proporção de aspecto do cinema scope?", v: "2.39:1", f: ["1.85:1", "16:9", "4:3"], img: "cinemascope widescreen aspect ratio" },
      { p: "Qual foi o primeiro filme a usar CGI para um personagem principal?", v: "Young Sherlock Holmes (1985)", f: ["Tron (1982)", "The Abyss (1989)", "Terminator 2 (1991)"], img: "early CGI character stained glass knight" },
      { p: "Qual cineasta usou 'tempo real' como narrativa em 'Rope'?", v: "Alfred Hitchcock", f: ["Orson Welles", "Billy Wilder", "Howard Hawks"], img: "Rope Hitchcock real-time single apartment" },
      { p: "Qual é o nome da abordagem documental que usa câmera tremida?", v: "Cinéma vérité / Direct cinema", f: ["Nouvelle Vague", "Neorrealismo", "Dogma 95"], img: "documentary handheld camera raw filming" },
      { p: "Qual filme tem o plano mais famoso de match cut da história?", v: "2001: Uma Odisseia no Espaço (osso → nave)", f: ["Lawrence da Arábia", "Psycho", "Citizen Kane"], img: "2001 Space Odyssey bone to satellite match cut" }
    ]
  }
};

module.exports = { BANCO_EXTRA };
